### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by coagulant** [mahmoudimus/nose-setenv#1]
Small but useful plugin!
Any ideas how to run it under python 3?
Doesn't work for me:

```
nose/plugins/manager.py:395: RuntimeWarning: Unable to load plugin nose_setenv = nose_setenv:SetEnvironmentVariables: cannot import name SetEnvironmentVariables
  RuntimeWarning)
Traceback (most recent call last):
  File "/.tox/py33-1.5.X/lib/python3.3/site-packages/nose/config.py", line 113, in _applyConfigurationToValues
    self._processConfigValue(name, value, values, parser)
  File "/.tox/py33-1.5.X/lib/python3.3/site-packages/nose/config.py", line 104, in _processConfigValue
    raise NoSuchOptionError(name)
nose.config.NoSuchOptionError: set-env-variables
```

**Comment by lancelote** [comment]
Quick note for fellow users - this issue seems to be fixed with e15038e9864804d7b8668c83c7d83e36616b93d9. Install `0.2.*` with:

```
pip isntall git+https://github.com/mahmoudimus/nose-setenv.git
```
